"""empty message

Revision ID: 1d81a6f35c51
Revises: cf0ec845887a
Create Date: 2021-05-05 06:34:32.154972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d81a6f35c51'
down_revision = 'cf0ec845887a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('seen', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'seen')
    # ### end Alembic commands ###
