"""empty message

Revision ID: 3e6268422f57
Revises: 1d81a6f35c51
Create Date: 2021-05-05 07:00:38.941663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6268422f57'
down_revision = '1d81a6f35c51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('reciever', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification', 'reciever')
    # ### end Alembic commands ###
