"""empty message

Revision ID: cf0ec845887a
Revises: 
Create Date: 2021-05-03 22:38:26.169403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0ec845887a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('sended_by', sa.Integer(), nullable=True),
    sa.Column('message_txt', sa.String(length=500), nullable=True),
    sa.Column('image', sa.String(length=200), nullable=True),
    sa.Column('emoji', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['sended_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('muted_users',
    sa.Column('muted_id', sa.Integer(), nullable=False),
    sa.Column('muted_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['muted_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('muted_id')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('notification_txt', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    op.drop_table('muted_users')
    op.drop_table('messages')
    op.drop_table('users')
    # ### end Alembic commands ###
